### ISSUE TITLE
I'm stumped on failure during mkmacboot()

### ISSUE THREAD

**Issue by jflorian** [rhinstaller/lorax#166]
I'm attempting to build a live image via our Koji and have gotten past most issues, but the following (from  livemedia-out.log) has me stumped:

```
2016-10-14 10:06:14,545 DEBUG pylorax.ltmpl: running command: ('mkefiboot', '--label=ANACONDA', '--apple', '--icon=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora.icns', '--diskname=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora-media.vol', '--product=mdct-aos-flash glenah', '/var/tmp/lmc-work-uq14bv7m/EFI/BOOT', '/var/tmp/lmc-work-uq14bv7m/images/macboot.img')
2016-10-14 10:06:15,046 DEBUG pylorax.ltmpl: command output:
Traceback (most recent call last):
  File "/usr/sbin/mkefiboot", line 167, in <module>
    main()
  File "/usr/sbin/mkefiboot", line 158, in main
    opt.diskname)
  File "/usr/sbin/mkefiboot", line 45, in mkmacboot
    mkhfsimg(None, outfile, label=label, graft=graft, size=size)
  File "/usr/lib/python3.5/site-packages/pylorax/imgutils.py", line 451, in mkhfsimg
    mkfsargs=["-v", label], graft=graft)
  File "/usr/lib/python3.5/site-packages/pylorax/imgutils.py", line 424, in mkfsimage
    with Mount(loopdev, mountargs) as mnt:
  File "/usr/lib/python3.5/site-packages/pylorax/imgutils.py", line 315, in __enter__
    self.mnt = mount(self.dev, self.opts, self.mnt)
  File "/usr/lib/python3.5/site-packages/pylorax/imgutils.py", line 198, in mount
    runcmd(cmd)
  File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 339, in runcmd
    return execWithRedirect(cmd[0], cmd[1:], **kwargs)
  File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 226, in execWithRedirect
    env_add=env_add, reset_handlers=reset_handlers, reset_lang=reset_lang)[0]
  File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 199, in _run_program
    raise subprocess.CalledProcessError(proc.returncode, argv, output)
subprocess.CalledProcessError: Command '['mount', '/dev/loop1', '/tmp/lorax.imgutils.kyxgf0lo']' returned non-zero exit status 32

2016-10-14 10:06:15,046 DEBUG pylorax.ltmpl: command returned failure (1)
2016-10-14 10:06:15,046 ERROR pylorax.ltmpl: template command error in x86.tmpl:
2016-10-14 10:06:15,047 ERROR pylorax.ltmpl:   runcmd mkefiboot --label=ANACONDA --apple --icon=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora.icns --diskname=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora-media.vol --product=mdct-aos-flash glenah /var/tmp/lmc-work-uq14bv7m/EFI/BOOT /var/tmp/lmc-work-uq14bv7m/images/macboot.img
2016-10-14 10:06:15,052 ERROR pylorax.ltmpl:   subprocess.CalledProcessError: Command '['mkefiboot', '--label=ANACONDA', '--apple', '--icon=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora.icns', '--diskname=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora-media.vol', '--product=mdct-aos-flash glenah', '/var/tmp/lmc-work-uq14bv7m/EFI/BOOT', '/var/tmp/lmc-work-uq14bv7m/images/macboot.img']' returned non-zero exit status 1
2016-10-14 10:06:15,052 DEBUG pylorax.ltmpl:   Traceback (most recent call last):
2016-10-14 10:06:15,053 DEBUG pylorax.ltmpl:     File "/usr/lib/python3.5/site-packages/pylorax/ltmpl.py", line 515, in runcmd
2016-10-14 10:06:15,053 DEBUG pylorax.ltmpl:       stdout = runcmd_output(cmd)
2016-10-14 10:06:15,053 DEBUG pylorax.ltmpl:     File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 345, in runcmd_output
2016-10-14 10:06:15,053 DEBUG pylorax.ltmpl:       return execWithCapture(cmd[0], cmd[1:], **kwargs)
2016-10-14 10:06:15,054 DEBUG pylorax.ltmpl:     File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 247, in execWithCapture
2016-10-14 10:06:15,054 DEBUG pylorax.ltmpl:       reset_handlers=reset_handlers, reset_lang=reset_lang)[1]
2016-10-14 10:06:15,054 DEBUG pylorax.ltmpl:     File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 199, in _run_program
2016-10-14 10:06:15,054 DEBUG pylorax.ltmpl:       raise subprocess.CalledProcessError(proc.returncode, argv, output)
2016-10-14 10:06:15,054 DEBUG pylorax.ltmpl:   subprocess.CalledProcessError: Command '['mkefiboot', '--label=ANACONDA', '--apple', '--icon=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora.icns', '--diskname=/var/tmp/lorax.imgutils.iyo8x2zq/usr/share/pixmaps/bootloader/fedora-media.vol', '--product=mdct-aos-flash glenah', '/var/tmp/lmc-work-uq14bv7m/EFI/BOOT', '/var/tmp/lmc-work-uq14bv7m/images/macboot.img']' returned non-zero exit status 1
```

Intuition tells me that mkefiboot fails because the mount in mkmacboot failed, but I've been unable to uncover why the mount fails.  Regardless, I've failed to grok why this happens and what I need to do about it.  I don't even need the macboot support as all my targets use BIOS boot, but it appears that Koji's LiveMediaTask class forces this if arch is x86_64.

I have been comparing notes heavily with a flattened fedora-live-xfce.ks but can't seem to find where I've went astray.  Any hints would be greatly appreciated!

**Comment by bcl** [comment]
I think that error means you're out of loop devices. I know I've seen it before, but it has been quite a while. I'll ask the obvious, even though I expect the answer is yes, does your koji setup have dgilmore's patches to create the loop devices inside the mock?

**Comment by bcl** [comment]
Also check the program.log to make sure the mkfs.hfsplus was executed properly.

**Comment by jflorian** [comment]
I hadn't considered the number of loop devices as an issue, especially given the failure was with loop1.  Nonetheless, I bumped it to 64 and confirmed that the Koji build host now has that many /dev/loop* nodes.  It still seems to fail in the same manner however.

As for the patches, I'm uncertain.  I can definitely state that this is an unmodified install of koji-1.10.1-8.el7 and koji-builder-1.10.1-8.el7 (on the build host) from EPEL.  (I was thinking I had something a bit atypical, but that was to resolve sigul + gpg2 issues using a repo that nirik pointed me to which Fedora uses.)  Any way, looking at "rpm -q --changelog koji-builder" doesn't show anything that sounds like what you described so maybe that's the problem?

As for program.log, there's no match on 'hfs' anywhere, though I can see hfsplus-tools getting installed in the livemedia-out.log.

**Comment by bcl** [comment]
Ah, RHEL/CentOS based. I'm not sure of the state of support for livemedia-creator in that codebase, but if it works at all it likely has the right stuff. This error is probably because hfs+ isn't supported by RHEL, but for some reason it is trying to execute it. The RHEL version of lmc defaults to --nomacboot so it shouldn't be trying to run mkfs.hfsplus.

**Comment by jflorian** [comment]
Sorry Brian, I should've mentioned that.  I wound up moving from a Fedora-based Koji+Sigul to a CentOS one because it looked nigh on impossible to get sigul going on an non-EoL Fedora.  nirik mentioned Fedora using EL for sigul and I just went all in.  The EL version of lmc default might be nomacboot, but it appears koji is forcing it:

`kojilogs/x86_64-27101/root.log:INFO backend.py:283:  Running in chroot: ['/sbin/livemedia-creator', '--ks', '/tmp/koji-image-f24-build-27101.ks', '--logfile', '/tmp/lmc-logs/livemedia-out.log', '--no-virt', '--resultdir', '/tmp/lmc', '--project', 'mdct-aos-flash', '--make-iso', '--volid', 'mdct-aos-flash-glenah-1', '--iso-only', '--iso-name', 'mdct-aos-flash-x86_64-glenah-1.iso', '--releasever', 'glenah', '--title', 'mdct-aos-flash', '--macboot']
`

Is that a bug then?  In the meantime, I'll whip of a F24 VM to occupy the livemedia channel alone to see if that helps.

**Comment by jflorian** [comment]
Success at last!  Creating an F24 build host did the trick.  I'm not clear why that makes a difference but this is good enough for me to continue my investigation into migrating our needs from livecd-creator + livecd-iso-to-disk to livemedia-creator + ???.

Thanks for all the help Brian!  You saved me gobs of time tracking this one down.  Please do let me know if you think a bug needs to be filed for the observation in my prior comment.

**Comment by bcl** [comment]
Glad to hear you got it sorted out. I'd expect that koji doesn't know much about building RHEL-like content, so it isn't really a bug. As you found, you need to have all the parts match up, not mix RHEL/Fedora.
