### ISSUE TITLE
mkefiboot macmunge IndexError: list index out of range

### ISSUE THREAD

**Issue by vanloswang** [rhinstaller/lorax#200]
On RHEL 7, with following packages:
livecd-tools-20.4-1.6.el7.x86_64
lorax-19.6.78-1.el7.x86_64
python-2.7.5-16.el7.x86_64

It fails while execute livecd-creator command, and the error info is as following:
```bash
Traceback (most recent call last):
  File "/sbin/mkefiboot", line 166, in <module>
    opt.diskname)
  File "/sbin/mkefiboot", line 46, in mkmacboot
    macmunge(outfile, product)
  File "/sbin/mkefiboot", line 73, in macmunge
    shim = glob.glob(os.path.join(mnt, 'EFI/BOOT/BOOT*.EFI'))[0]
IndexError: list index out of range
```

After copy the macboot.img and mount it by loop device, and write a test code, I found out that the 'glob.glob(os.path.join(mnt, 'EFI/BOOT/BOOT*.EFI'))' returns a empty list.  So it will crash on where to get the first element of the list. The data 'BOOT*.EFI' in macboot.img is renamed to lower suffix, such as BOOTX64.efi. we need to adjust the code to adopt to this change, for example:
```bash
            shimList = glob.glob(os.path.join(mnt, 'EFI/BOOT/BOOT*.EFI'))
            if len(shimList):
                pass
            else:
                shimList = glob.glob(os.path.join(mnt, 'EFI/BOOT/BOOT*.efi'))
            shim = shimList[0]
```

**Comment by vanloswang** [comment]
After make such a change to the original code, then meet following crash:
```bash
Traceback (most recent call last):
  File "/sbin/mkefiboot", line 158, in <module>
    opt.diskname)
  File "/sbin/mkefiboot", line 45, in mkmacboot
    macmunge(outfile, product)
  File "/sbin/mkefiboot", line 88, in macmunge
    shutil.copy(shim, os.path.join(sysdir,'boot.efi'))
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: '/'
```
