### ISSUE TITLE
Fedora 25 no '-e' option in mkisofs

### ISSUE THREAD

**Issue by voor** [rhinstaller/lorax#205]
```
lorax-templates-generic-25.19-1.fc25.x86_64
lorax-25.19-1.fc25.x86_64
mkisofs-3.02-a07.2.fc25.x86_64
```
Results in the following:

```
command finished successfully
template line 51: runcmd mkisofs -o /root/results/images/boot.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -boot-load-size 4 -boot-info-table -no-emul-boot -eltorito-alt-boot -e images/efiboot.img -no-emul-boot -eltorito-alt-boot -e images/macboot.img -no-emul-boot -R -J -V Fedora-Generic-25-x86_64 -T -graft-points images/install.img=/root/results/images/install.img isolinux=/root/results/isolinux images/pxeboot=/root/results/images/pxeboot EFI/BOOT=/root/results/EFI/BOOT images/efiboot.img=/root/results/images/efiboot.img images/macboot.img=/root/results/images/macboot.img
running command: ('mkisofs', '-o', '/root/results/images/boot.iso', '-b', 'isolinux/isolinux.bin', '-c', 'isolinux/boot.cat', '-boot-load-size', '4', '-boot-info-table', '-no-emul-boot', '-eltorito-alt-boot', '-e', 'images/efiboot.img', '-no-emul-boot', '-eltorito-alt-boot', '-e', 'images/macboot.img', '-no-emul-boot', '-R', '-J', '-V', 'Fedora-Generic-25-x86_64', '-T', '-graft-points', 'images/install.img=/root/results/images/install.img', 'isolinux=/root/results/isolinux', 'images/pxeboot=/root/results/images/pxeboot', 'EFI/BOOT=/root/results/EFI/BOOT', 'images/efiboot.img=/root/results/images/efiboot.img', 'images/macboot.img=/root/results/images/macboot.img')
command output:
Bad Option '-e' (error -1 BADFLAG).
Usage: mkisofs [options] [-find] file... [find expression]

Use mkisofs -help
to get a list all of valid options.

Use mkisofs -find -help
to get a list of all valid -find options.

Most important Options:
	-posix-H		Follow sylinks encountered on command line
	-posix-L		Follow all symlinks
	-posix-P		Do not follow symlinks (default)
	-o FILE, -output FILE	Set output file name
	-R, -rock		Generate Rock Ridge directory information
	-r, -rational-rock	Generate rationalized Rock Ridge directory info
	-J, -joliet		Generate Joliet directory information
	-print-size		Print estimated filesystem size and exit
	-UDF			Generate UDF file system
	-dvd-audio		Generate DVD-Audio compliant UDF file system
	-dvd-video		Generate DVD-Video compliant UDF file system
	-dvd-hybrid		Generate a hybrid (DVD-Audio/DVD-Video) compliant UDF file system
	-iso-level LEVEL	Set ISO9660 level (1..3) or 4 for ISO9660 v 2
	-V ID, -volid ID	Set Volume ID
	-graft-points		Allow to use graft points for filenames
	-M FILE, -prev-session FILE	Set path to previous session to merge

command returned failure (255)
template command error in x86.tmpl:
  runcmd mkisofs -o /root/results/images/boot.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -boot-load-size 4 -boot-info-table -no-emul-boot -eltorito-alt-boot -e images/efiboot.img -no-emul-boot -eltorito-alt-boot -e images/macboot.img -no-emul-boot -R -J -V Fedora-Generic-25-x86_64 -T -graft-points images/install.img=/root/results/images/install.img isolinux=/root/results/isolinux images/pxeboot=/root/results/images/pxeboot EFI/BOOT=/root/results/EFI/BOOT images/efiboot.img=/root/results/images/efiboot.img images/macboot.img=/root/results/images/macboot.img
  subprocess.CalledProcessError: Command '['mkisofs', '-o', '/root/results/images/boot.iso', '-b', 'isolinux/isolinux.bin', '-c', 'isolinux/boot.cat', '-boot-load-size', '4', '-boot-info-table', '-no-emul-boot', '-eltorito-alt-boot', '-e', 'images/efiboot.img', '-no-emul-boot', '-eltorito-alt-boot', '-e', 'images/macboot.img', '-no-emul-boot', '-R', '-J', '-V', 'Fedora-Generic-25-x86_64', '-T', '-graft-points', 'images/install.img=/root/results/images/install.img', 'isolinux=/root/results/isolinux', 'images/pxeboot=/root/results/images/pxeboot', 'EFI/BOOT=/root/results/EFI/BOOT', 'images/efiboot.img=/root/results/images/efiboot.img', 'images/macboot.img=/root/results/images/macboot.img']' returned non-zero exit status 255
  Traceback (most recent call last):
    File "/usr/lib/python3.5/site-packages/pylorax/ltmpl.py", line 515, in runcmd
      stdout = runcmd_output(cmd)
    File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 347, in runcmd_output
      return execWithCapture(cmd[0], cmd[1:], **kwargs)
    File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 249, in execWithCapture
      reset_handlers=reset_handlers, reset_lang=reset_lang)[1]
    File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 201, in _run_program
      raise subprocess.CalledProcessError(proc.returncode, argv, output)
  subprocess.CalledProcessError: Command '['mkisofs', '-o', '/root/results/images/boot.iso', '-b', 'isolinux/isolinux.bin', '-c', 'isolinux/boot.cat', '-boot-load-size', '4', '-boot-info-table', '-no-emul-boot', '-eltorito-alt-boot', '-e', 'images/efiboot.img', '-no-emul-boot', '-eltorito-alt-boot', '-e', 'images/macboot.img', '-no-emul-boot', '-R', '-J', '-V', 'Fedora-Generic-25-x86_64', '-T', '-graft-points', 'images/install.img=/root/results/images/install.img', 'isolinux=/root/results/isolinux', 'images/pxeboot=/root/results/images/pxeboot', 'EFI/BOOT=/root/results/EFI/BOOT', 'images/efiboot.img=/root/results/images/efiboot.img', 'images/macboot.img=/root/results/images/macboot.img']' returned non-zero exit status 255
```

After running this:

```
lorax -p Fedora-Generic -v 25 -r 25 -s https://mirror.umd.edu/fedora/linux/releases/25/Everything/x86_64/os/ -s https://mirror.umd.edu/fedora/linux/updates/25/x86_64/ ./results
```

**Comment by bcl** [comment]
I ran into this earlier this year as well, my system was using mkisofs from rpmfusion I believe it was, which doesn't support UEFI. The correct package to use is genisoimage.

**Comment by voor** [comment]
Installing `genisoimage` fixed the problem, thank you!

**Comment by RSully** [comment]
Which option `-e` is it supposed to use? I get this error now for `-e` from `genisoimage`:

> genisoimage: option '-e' is ambiguous; possibilities: '--eltorito-boot' '--exchange' '--ethershare' '--exclude-list' '--exclude' '--eltorito-catalog' '--eltorito-alt-boot'

**Comment by bcl** [comment]
`-e` is used to set the efi boot image.
Which release are you seeing this in? And which version of genisoimage? You should make sure you have the fedora version of the tools installed for your release.

**Comment by adam-erickson** [comment]
I believe the `-e` flag is equivalent to the `-eltorito-boot` flag.
