### ISSUE TITLE
x86.tmpl fails when running mkefiboot (exit status 1)

### ISSUE THREAD

**Issue by frafra** [rhinstaller/lorax#211]
```
# livemedia-creator --ks tools/serveurlibre-flat.ks --no-virt --make-iso --iso-only --iso-name ServeurLibre.iso --volid ServeurLibre --title ServeurLibre --releasever 25 --proxy=http://localhost:3128
[...]
2017-05-22 20:12:03,268: Building boot.iso
2017-05-22 20:12:03,394: running x86.tmpl
2017-05-22 20:12:08,103: template command error in x86.tmpl:
2017-05-22 20:12:08,103:   runcmd mkefiboot --label=ANACONDA /var/tmp/lmc-work-55byjqxr/EFI/BOOT /var/tmp/lmc-work-55byjqxr/images/efiboot.img
2017-05-22 20:12:08,106:   subprocess.CalledProcessError: Command '['mkefiboot', '--label=ANACONDA', '/var/tmp/lmc-work-55byjqxr/EFI/BOOT', '/var/tmp/lmc-work-55byjqxr/images/efiboot.img']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/sbin/livemedia-creator", line 1476, in <module>
    main()
  File "/usr/sbin/livemedia-creator", line 1413, in main
    result_dir = make_livecd(opts, mount_dir, work_dir)
  File "/usr/sbin/livemedia-creator", line 637, in make_livecd
    tb.build()
  File "/usr/lib/python3.5/site-packages/pylorax/treebuilder.py", line 308, in build
    self._runner.run(templatefile, kernels=self.kernels)
  File "/usr/lib/python3.5/site-packages/pylorax/ltmpl.py", line 220, in run
    self._run(commands)
  File "/usr/lib/python3.5/site-packages/pylorax/ltmpl.py", line 239, in _run
    f(*args)
  File "/usr/lib/python3.5/site-packages/pylorax/ltmpl.py", line 515, in runcmd
    stdout = runcmd_output(cmd)
  File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 347, in runcmd_output
    return execWithCapture(cmd[0], cmd[1:], **kwargs)
  File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 249, in execWithCapture
    reset_handlers=reset_handlers, reset_lang=reset_lang)[1]
  File "/usr/lib/python3.5/site-packages/pylorax/executils.py", line 201, in _run_program
    raise subprocess.CalledProcessError(proc.returncode, argv, output)
subprocess.CalledProcessError: Command '['mkefiboot', '--label=ANACONDA', '/var/tmp/lmc-work-55byjqxr/EFI/BOOT', '/var/tmp/lmc-work-55byjqxr/images/efiboot.img']' returned non-zero exit status 1
```

I executed the command by myself and it worked just fine:
```
# mkefiboot --label=ANACONDA /var/tmp/lmc-work-55byjqxr/EFI/BOOT /var/tmp/lmc-work-55byjqxr/images/efiboot.img ; echo $?
0
```

I tried to cleanup the mock environment and to run the procedure multiple times, but the problem persists. I am using F25 x86_64.

**Comment by frafra** [comment]
I rebooted the system, cleaned the environment and it worked. Sometimes I encounter generic errors because some component is missing. It would be nice to have a verbose/debug flag.

**Comment by bcl** [comment]
Running things in mock and having them fail can leave /dev/loop* mounted in some cases. When I've seen mkefiboot fail like this it is usually because the system has run out of free loop devices.
