### ISSUE TITLE
Install packages failed in cross build environment

### ISSUE THREAD

**Issue by lin755** [rhinstaller/lorax#301]
**HOST:X86 ubuntu**
**DOCKER:arm64 centos 7**
2018-01-10 18:35:11,137: template command error in runtime-postinstall.tmpl:
template command error in runtime-postinstall.tmpl:
2018-01-10 18:35:11,138:   symlink /lib/systemd/system/anaconda.target etc/systemd/system/default.target
  symlink /lib/systemd/system/anaconda.target etc/systemd/system/default.target
2018-01-10 18:35:11,157:   OSError: [Errno 2] No such file or directory
  OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/sbin/lorax", line 337, in <module>
    main(sys.argv)
  File "/usr/sbin/lorax", line 235, in main
    remove_temp=True)
  File "/usr/lib/python2.7/site-packages/pylorax/__init__.py", line 272, in run
    rb.postinstall()
  File "/usr/lib/python2.7/site-packages/pylorax/treebuilder.py", line 136, in postinstall
    self._runner.run("runtime-postinstall.tmpl", configdir=configdir_path)
  File "/usr/lib/python2.7/site-packages/pylorax/ltmpl.py", line 182, in run
    self._run(commands)
  File "/usr/lib/python2.7/site-packages/pylorax/ltmpl.py", line 201, in _run
    f(*args)
  File "/usr/lib/python2.7/site-packages/pylorax/ltmpl.py", line 359, in symlink
    os.symlink(target, self._out(dest))
OSError: [Errno 2] No such file or directory
2018-01-10 18:35:11,360: glibc-2.17-196.el7.aarch64 scriptlet output:
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from dbcursor->c_close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery

glibc-2.17-196.el7.aarch64 scriptlet output:
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from dbcursor->c_close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery

2018-01-10 18:35:11,614: RPM transaction error: Error: Cannot open file /var/tmp/lorax.ffv2RL/installtree/var/tmp/lorax.ffv2RL/yum/yum.cache/lorax-repo/packages/libstdc++-4.8.5-16.el7.aarch64.rpm: [Errno 2] No such file or directory: '/var/tmp/lorax.ffv2RL/installtree/var/tmp/lorax.ffv2RL/yum/yum.cache/lorax-repo/packages/libstdc++-4.8.5-16.el7.aarch64.rpm'
RPM transaction error: Error: Cannot open file /var/tmp/lorax.ffv2RL/installtree/var/tmp/lorax.ffv2RL/yum/yum.cache/lorax-repo/packages/libstdc++-4.8.5-16.el7.aarch64.rpm: [Errno 2] No such file or directory: '/var/tmp/lorax.ffv2RL/installtree/var/tmp/lorax.ffv2RL/yum/yum.cache/lorax-repo/packages/libstdc++-4.8.5-16.el7.aarch64.rpm'
TypeError: an integer is required
FATAL ERROR: python callback <bound method RPMTransaction.callback of <yum.rpmtrans.RPMTransaction instance at 0xfc93f8>> failed, aborting!

**Comment by lin755** [comment]
2018-01-10 10:32:57,299: RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package gnome-keyring-3.20.0-3.el7.aarch64
RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package gnome-keyring-3.20.0-3.el7.aarch64
2018-01-10 10:32:57,597: gnome-themes-standard.aarch64 0:3.22.2-1.el7 - u scriptlet output:
warning: %posttrans(gnome-themes-standard-3.22.2-1.el7.aarch64) scriptlet failed, exit status 127

gnome-themes-standard.aarch64 0:3.22.2-1.el7 - u scriptlet output:
warning: %posttrans(gnome-themes-standard-3.22.2-1.el7.aarch64) scriptlet failed, exit status 127

2018-01-10 10:32:57,733: RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package gnome-themes-standard-3.22.2-1.el7.aarch64
RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package gnome-themes-standard-3.22.2-1.el7.aarch64
2018-01-10 10:32:58,032: kernel.aarch64 0:4.12.0-estuary.4 - i scriptlet output:
warning: %posttrans(kernel-4.12.0-estuary.4.aarch64) scriptlet failed, exit status 127

kernel.aarch64 0:4.12.0-estuary.4 - i scriptlet output:
warning: %posttrans(kernel-4.12.0-estuary.4.aarch64) scriptlet failed, exit status 127

2018-01-10 10:32:58,159: RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package kernel-4.12.0-estuary.4.aarch64
RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package kernel-4.12.0-estuary.4.aarch64
2018-01-10 10:32:58,477: gnome-icon-theme-legacy.noarch 0:3.12.0-1.el7 - u scriptlet output:
warning: %posttrans(gnome-icon-theme-legacy-3.12.0-1.el7.noarch) scriptlet failed, exit status 127

gnome-icon-theme-legacy.noarch 0:3.12.0-1.el7 - u scriptlet output:
warning: %posttrans(gnome-icon-theme-legacy-3.12.0-1.el7.noarch) scriptlet failed, exit status 127

2018-01-10 10:32:58,634: RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package gnome-icon-theme-legacy-3.12.0-1.el7.noarch
RPM transaction error: Non-fatal POSTTRANS scriptlet failure in rpm package gnome-icon-theme-legacy-3.12.0-1.el7.noarch
2018-01-10 18:35:02,809: package 'gdb-7.6.1-100.el7.aarch64' was not installed
package 'gdb-7.6.1-100.el7.aarch64' was not installed
2018-01-10 18:35:02,810: package 'iptables-1.4.21-18.el7.aarch64' was not installed
package 'iptables-1.4.21-18.el7.aarch64' was not installed
2018-01-10 18:35:02,811: package 'openssh-server-7.4p1-11.el7.aarch64' was not installed
package 'openssh-server-7.4p1-11.el7.aarch64' was not installed
2018-01-10 18:35:02,813: package 'GConf2-3.2.6-8.el7.aarch64' was not installed
package 'GConf2-3.2.6-8.el7.aarch64' was not installed
2018-01-10 18:35:02,814: package 'trousers-0.3.14-2.el7.aarch64' was not installed
package 'trousers-0.3.14-2.el7.aarch64' was not installed
2018-01-10 18:35:02,815: package 'polkit-0.112-13.p1.el7a.aarch64' was not installed
package 'polkit-0.112-13.p1.el7a.aarch64' was not installed
2018-01-10 18:35:02,816: package '12:dhclient-4.2.5-58.el7.aarch64' was not installed
package '12:dhclient-4.2.5-58.el7.aarch64' was not installed
2018-01-10 18:35:02,817: package 'xml-common-0.6.3-39.el7.noarch' was not installed
package 'xml-common-0.6.3-39.el7.noarch' was not installed
2018-01-10 18:35:02,818: package '1:dbus-1.6.12-17.el7.aarch64' was not installed
package '1:dbus-1.6.12-17.el7.aarch64' was not installed
2018-01-10 18:35:02,819: package 'ca-certificates-2017.2.14-71.el7.noarch' was not installed
package 'ca-certificates-2017.2.14-71.el7.noarch' was not installed
2018-01-10 18:35:02,820: package 'geoclue2-2.4.5-1.el7.aarch64' was not installed
package 'geoclue2-2.4.5-1.el7.aarch64' was not installed
2018-01-10 18:35:02,821: package '1:smartmontools-6.2-8.el7.aarch64' was not installed
